id: A65D7699D
title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
type: translation
pechas:
- I77254AD2
- I84C2541A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:39.433101
  last_modified_at: 2023-01-04 11:36:39.433114
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I77254AD2/849A: 70F6
  I84C2541A/4246: 70F6
